### PR TITLE
Making content type param configurable per adapter

### PR DESCRIPTION
**Pull request by morganick**
This makes it easy to match the api identifier for the content model
you specified inside of Contentful.

### CODE REVIEW

**Comment by morganick** [comment]
I'm not sold on the name of the method because in Contentful they call it API identifier and then it's passed in as the `content_type` for the request.

**Review by davidpett — COMMENTED** [review]
I think I would rather just pass the string type.modelName to the method instead of the type object

**Comment by morganick** [comment]
@davidpett I apologize for the delayed response. I did not see the notification that you had responded to this PR. I have made the suggested edit.

**Comment by acorncom** [comment]
@morganick tests failed here

**Comment by morganick** [comment]
@acorncom unfortunately, I don't believe that has anything to do with the code as there are no tests. Only that we did not get the version of ember that we were expecting.

**Comment by morganick** [comment]
@davidpett I've run the tests locally several times and had it break once. I can't seem to replicate the failure consistently. Ideas?

**Comment by davidpett** [comment]
my only guess is that the travis config needs to be updated. let me get that fixed and have these run again

**Comment by morganick** [comment]
Thanks @davidpett!

**Comment by davidpett** [comment]
@morganick looks like Travis is having some issues, probably related to aws outages. Hopefully it completes and all is well

**Review by davidpett — APPROVED** [review]

**Comment by davidpett** [comment]
currently no tests anyway, bypassing travis build

**Comment by davidpett** [comment]
released 0.2.1

**Pull request merged**
