### PR TITLE
Add support for Preview API

### PR DESCRIPTION
**Pull request by gpxl**

### CODE REVIEW

**Comment by davidpett** [comment]
Thanks, I have been wanting to add this option, but want to make it configurable to the user and not default if the configuration is set. do you think maybe using a queryParam or something to enable would be a good option?

**Comment by gpxl** [comment]
I like the queryParam idea but would it be easy to carry that param through as a user navigates an app? I'm new to Ember so IDK if that's an obviously easy thing.

**Comment by davidpett** [comment]
I made a few adjustments to accommodate a configuration variable for the preview API, i still want it to be configurable some other way, but a toggle of some sort may not work because of data that has already been loaded: https://github.com/davidpett/ember-data-contentful/blob/master/addon/adapters/contentful.js#L186-L199 any more suggestions would be great. If not, I will cut a new release

**Comment by gpxl** [comment]
I have no further suggestions at the moment. Thanks!

**Comment by davidpett** [comment]
Published the new release. Also added a base contentful model and a contentful-asset model which include the contentType, createdAt, and updatedAt properties

**Pull request merged**
