### PR TITLE
Beginnings of tests for the Contentful serializer

### PR DESCRIPTION
**Pull request by morganick**
Couple of things that I noticed in doing this:

First, `queryRecord` does not set the limit in the adapter:
https://github.com/davidpett/ember-data-contentful/blob/master/addon/adapters/contentful.js#L165

So as you can see in the test the limit is set at default of 100. I have another branch that fixes this but I wanted to point that out. ( Setting the skip to 0 is key here too.)

Second, the type is not present for the record inside of `data`. It appears that ember-data does the right thing, but I haven't taken the time to really dig in on that yet.

Unfortunately, the tests are long because the data is verbose that comes back from Contentful. We could probably use fixtures? (I haven't used them yet in tests so...)

I'm sure I'm forgetting something but 😪 

I'll dive back in tomorrow. Happy Friday 🎉

### CODE REVIEW

**Comment by morganick** [comment]
So couple of things I found out... having a `maxDepth` of 5 is problematic because Contentful's JSON payload has multiple levels of nested data structures. (Also, https://github.com/testem/testem/issues/962)

This makes the tests longer because of so many asserts; however, I expect most of it to go away once I have tests on `normalize`. That will probably end up being the most verbose test and the others will rely on that to test the result ends up in the right places in the JSONAPI document.

Fixtures/factories would probably be good here to trim down the data inside of the test.

Any feedback on this would be welcome 😄

**Comment by morganick** [comment]
@davidpett would you mind connecting TravisCI to the repo again? I want to make sure it works somewhere besides my local dev env.

**Comment by davidpett** [comment]
@morganick travis is connected again and passing

**Comment by morganick** [comment]
Thanks @davidpett 🎉   More on the way.

**Comment by davidpett** [comment]
I just updated some stuff on the dummy app, shouldn't affect anything you are doing.

Thanks again for the help. If you prefer, I can add you as a collaborator to the project. Let me know.

**Comment by morganick** [comment]
@davidpett I've run the test suite locally without issue. I'm wondering if Travis has a build cache issue? I don't have the option to rebuild the project without cache. Do you have an option to do so?

**Comment by morganick** [comment]
🎉

**Comment by davidpett** [comment]
thanks!

**Comment by morganick** [comment]
fixes #20

**Pull request merged**
