### PR TITLE
Update to Ember 3.1 & Babel 6.8.2

### PR DESCRIPTION
**Pull request by jonnygreen**

### CODE REVIEW

**Comment by amyrlam** [comment]
Just saw this, thanks @jonnygreen! I took a stab at a couple dependencies in WIP PR https://github.com/davidpett/ember-data-contentful/pull/31, but this PR covers that and more, with passing CI. 

@davidpett can you bump a new version if you're ok with merging these changes?

**Comment by davidpett** [comment]
just released 0.2.4, thanks for the work @jonnygreen and @amyrlam 

If either of you would like to take over maintaining this project, please let me know as I am no longer able to

**Comment by amyrlam** [comment]
Thanks @davidpett! 💯

I just started using the library, and may need to loop in more help, but def down to help take over!

**Comment by jonnygreen** [comment]
Thanks @davidpett. If things go to plan then I’ll be working with Contentful more, and have the support network to look after this. Too early to say at the moment though

**Comment by amyrlam** [comment]
I started using 0.2.4! I found that I need to use `ember install` over a `npm install`, need to dig into it more. 

Keep me posted about the library, want to help keep it going! 👍

**Pull request merged**
